<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM3Za4la\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM3Za4la/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM3Za4la.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM3Za4la\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM3Za4la\App_KernelDevDebugContainer([
    'container.build_hash' => 'M3Za4la',
    'container.build_id' => '6a5ccc5e',
    'container.build_time' => 1652534077,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM3Za4la');
